version: "3.3"

services:
  database:
    image: postgis/postgis:12-3.0
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgresql:/docker-entrypoint-initdb.d:ro
    restart: always
    networks:
      - database-compose-network

  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: rabbitmq_management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmquser
      RABBITMQ_DEFAULT_PASS: rabbitmqpassword
      RABBITMQ_QUEUE_NAME: clients
      RABBITMQ_QUEUE_DURABLE: "true"
    # volumes:
    #   - ./definitions.json:/etc/definitions.json
    # command: rabbitmq-server --load-definitions /etc/definitions.json
    restart: always
    networks:
      - database-compose-network

  app:
    build:
      context: ./app/deployment
      args:
        - GITHUB_TOKEN=<seu_token>
        - DATABASE_URL=postgres://postgres:postgres@localhost:5432/postgres?sslmode=disable
        - RABBITMQ_URI=amqp://rabbitmquser:rabbitmqpassword@localhost:5672/
        - QUEUE_NAME=clients
        - ROUTING_KEY=mapping.position
        - EXCHANGE_NAME=clients
        - EXCHANGE_TYPE=direct
    ports:
      - 8080:8080
    environment:
      - GAE_ENV=production
    depends_on:
      - database
      - rabbitmq
    restart: always
    networks:
      - database-compose-network
    
  worker:
    build:
      context: ./worker/deployment
      args:
        - GITHUB_TOKEN=<seu_token>
        - DATABASE_URL=postgres://postgres:postgres@localhost:5432/postgres?sslmode=disable
        - RABBITMQ_URI=amqp://rabbitmquser:rabbitmqpassword@localhost:5672/
        - QUEUE_NAME=clients
    ports:
      - 8081:8081
    environment:
      - GAE_ENV=production
    depends_on:
      - database
      - rabbitmq
    restart: always
    networks:
      - database-compose-network

networks:
  database-compose-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local